version: '3'

services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipelines
    environment:
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - MKL_THREADING_LAYER=GNU
    volumes:
      - ./:/PMC
      - ./../Datasets:/Datasets
    networks:
      - app_network
    command: tail -F /dev/null

  unsupervised_learning:
    build:
      context: .
      dockerfile: Dockerfile.unsupervised
    volumes:
      - ./:/PMC
      - ./../Datasets:/Datasets
    networks:
      - app_network
    command: bash -c "nvidia-smi && tail -F /dev/null"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    devices: 
      - "/dev/video0:/dev/video0"


  supervised_learning:
    build:
      context: .
      dockerfile: Dockerfile.supervised
    environment:
      - MKL_THREADING_LAYER=GNU
    volumes:
      - ./:/PMC
      - ./../Datasets:/Datasets
    networks:
      - app_network
    command: tail -F /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  dataset:

networks:
  app_network:
    driver: bridge
