version: '3'

services:
  pipeline:
    privileged: true 
    build:
      context: .
      dockerfile: Dockerfile.pipelines
    environment:
      - MKL_THREADING_LAYER=GNU
    volumes:
      - ./:/PMC
      - ./../Datasets:/Datasets
    networks:
      - app_network
    command: tail -F /dev/null
    ports:
      - "8080:8080" # Port pour la communication
    devices: 
      - "/dev/video0:/dev/video0"
      # - "/dev/video2:/dev/video2"
      # - "/dev/video4:/dev/video4" # Additional camera
      # - "/dev/video6:/dev/video6" # Additional camera

  unsupervised_learning:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.unsupervised
    volumes:
      - ./:/PMC
      - ./../Datasets:/Datasets
    networks:
      - app_network
    ports:
      - "8081:8081" # Port pour la communication
    command: bash -c "nvidia-smi && tail -F /dev/null"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  supervised_learning:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.supervised
    environment:
      - MKL_THREADING_LAYER=GNU
    volumes:
      - ./:/PMC
      - ./../Datasets:/Datasets
    networks:
      - app_network
    ports:
      - "8082:8082" # Port pour la communication
    command: tail -F /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  dataset:

networks:
  app_network:
    driver: bridge
