wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0rc1
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709581572.455844
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.0rc1
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.001
