wandb_version: 1

encoding_dim:
  desc: null
  value: 16
lr:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 34
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707762272.011446
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 16
      - 23
      4: 3.11.4
      5: 0.16.3
      8:
      - 5
      10:
      - 9
      13: linux-x86_64
